### ISSUE TITLE
Can not find mapgen.launch

### ISSUE THREAD

**Issue by Vilour** [LimHyungTae/ERASOR#1]
When I run step 1, 

`roslaunch erasor mapgen.launch`

This command failed. Is mappgen.launch missing?

**Comment by LimHyungTae** [comment]
Oops, my bad.
I uploaded mapgen.launch. It is due to my predefined .gitignore file haha...Please git clone again.
Thank you for your kind interest!

**Comment by Vilour** [comment]
Thank you! Awesome work!
The code works on KITTI data very well!
Looking forward the guidance on "Run Your Own Code"!
