### ISSUE TITLE
use HDL 32E Velodyne's  data

### ISSUE THREAD

**Issue by pytorch1100** [LimHyungTae/ERASOR#11]
Hi @LimHyungTae， thank you for your great work! I have one question. If i use Velodyne 32E's data, what parameters should be changed? The parameters of Lidar are below. 
![image](https://user-images.githubusercontent.com/59380928/156770517-389d99db-6ad3-4295-9de1-bfdc6e0468fa.png)

**Comment by pytorch1100** [comment]
The distance between lidar and the ground is shown in the figure below, which is 1.8m. If I want to change the min_h in the code, can I use  min_h = -1.8m?
![image](https://user-images.githubusercontent.com/59380928/156772019-ec2d3725-a510-498d-96e3-2430c44f2ebc.png)

**Comment by darshanAtSwaayatt** [comment]
Hi @pytorch1100,

Were you able to figure out what parameters to change for HDL 32E Velodyne lidar?
