### ISSUE TITLE
can not find compare_results.launch

### ISSUE THREAD

**Issue by crankler** [LimHyungTae/ERASOR#2]
Thank you for sharing your interesting work, @LimHyungTae 
But I can't find this command:

```
roslaunch erasor compare_results.launch
```
Can you update this missng file?

**Comment by LimHyungTae** [comment]
Oops, sorry for the late response due to the ICRA'22.

I'll upload it ASAP!!!!

**Comment by LimHyungTae** [comment]
I uploaded it. Sorry for late reply!
