### ISSUE TITLE
A question about PR and RR calculation

### ISSUE THREAD

**Issue by duanxz0127** [LimHyungTae/ERASOR#36]
Thank you very much for your excellent work on this project. However, I have a small question regarding the accuracy evaluation script.

In the function 
```
calc_naive_preservation(gt, estimate, dists, indices, voxelsize)
```
why ```num_dynamic_preserved``` is ```(gt_sem in DYNAMIC_CLASSES) and (est_sem in DYNAMIC_CLASSES)```, which counts the number of points where "both are dynamic"? Based on my understanding of the ERASOR paper, num_dynamic_preserved refers to the number of dynamic points retained in the estimated static map. Shouldn't this value be determined by ```(gt_sem not in DYNAMIC_CLASSES) and (est_sem in DYNAMIC_CLASSES)``` instead?

If my understanding is incorrect, I would greatly appreciate it if you could clarify. Thank you again for your work!

**Comment by LimHyungTae** [comment]
Have you resolved your question? `num_dynamic_preserved` to count remaining moving points.

**Comment by duanxz0127** [comment]
> Have you resolved your question? `num_dynamic_preserved` to count remaining moving points.

Thank you for your response. I have resolved my question. 
I had previously incorrectly assumed that the input was a categorized point cloud rather than a static point cloud map. lol
