### ISSUE TITLE
ERROR, when i run "roslaunch erasor run_erasor_in_your_env.launch"

### ISSUE THREAD

**Issue by llxClover** [LimHyungTae/ERASOR#4]
`main_in_your_env: /usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:110: Eigen::internal::variable_if_dynamic<T, Value>::variable_if_dynamic(T) [with T = long int; int Value = 3]: Assertion `v == T(Value)' failed.
[main_in_your_env-2] process has died [pid 32096, exit code -6, cmd /home/dt/ROS_WS/erasor_ws/devel/lib/erasor/main_in_your_env __name:=main_in_your_env __log:=/home/dt/.ros/log/5305fe14-348b-11ec-9ebf-081f7134fb94/main_in_your_env-2.log].
log file: /home/dt/.ros/log/5305fe14-348b-11ec-9ebf-081f7134fb94/main_in_your_env-2*.log`

**Comment by MIke-1118** [comment]
Hi ! I met the problem too! Have you solved the problem?

**Comment by p-CXTN** [comment]
Apparently it's a misuse of `Eigen::Matrix::topLeftCorner`, I just changed [line51](https://github.com/LimHyungTae/ERASOR/blob/master/src/offline_map_updater/main_in_your_env.cpp) in `main_in_your_env.cpp` from

``` C++
tf4x4_cam.topLeftCorner<3, 3>(0, 0) = q.toRotationMatrix();
```

 to 

```C++
tf4x4_cam.block<3, 3>(0, 0) = q.normalized().toRotationMatrix();
```

or

```C++
tf4x4_cam.topLeftCorner(3, 3) = q.normalized().toRotationMatrix();
```

and it works. 

BTW at [line52](https://github.com/LimHyungTae/ERASOR/blob/master/src/offline_map_updater/main_in_your_env.cpp) there's a correct use of `Eigen::Matrix::topRightCorner`:
> ``` C++
> tf4x4_cam.topRightCorner(3, 1) = ts.vector();
> ```
so I'm sure the author just mixed up `Eigen::Matrix::topLeftCorner()` and `Eigen::Matrix::block()`.
