### ISSUE TITLE
catkin build error: can not find erasor/node.h.

### ISSUE THREAD

**Issue by zxczrx123** [LimHyungTae/ERASOR#8]
Thanks for your great work!  According to your introduction, I encountered the following problem. I can't find node.h from the source file. @LimHyungTae
![image](https://user-images.githubusercontent.com/37107333/154635115-08ce2032-1ae3-4ac9-a307-f6da6b3eff0e.png)
Could you please give me some help? 🥺

**Comment by LimHyungTae** [comment]
Hmm....well could you build the repo after comment out of all `add_executable`, `target_link_libraries`, and `add_dependencies `lines? Then, msg would be successfully compiled. Then, please recompile this repo again!

**Comment by zxczrx123** [comment]
Thanks for your reply! Actually, I have solved this problem by using `catkin_make`.
